# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:14 
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
      # username: postgres
      # db: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
